##########################
# Name: Advait Ramesh Iyer
# Homework 3
##########################

fname <- file.choose()
art <- read.csv(fname, header = TRUE, stringsAsFactors = FALSE)

colnames(art)

# Output:
# [1] "date"       "year"       "rep"        "store"      "paper"      "paper.type" "unit.price"
# [8] "units.sold" "total.sale"

# Understanding the contents of the dataset
str(art)
summary(art)

################################################################################################

# Question 1: Is there a relationship between the unit price of art goods and their units sold? 
# If so, what kind of relationship is it?

class(art$unit.price)
class(art$units.sold)
par(mfrow=c(2,2))
plot(art$unit.price,art$units.sold, ylab = "Units Sold", xlab = "Unit Price (in Dollars)"
     , main = "Units sold by Unit Price", pch="M",bty="o")
clip(-5, max(art$unit.price), 0, max(art$units.sold))
abline(lm(art$units.sold ~ art$unit.price), lwd = 3, col="red")

# In the plot, it is clearly visible that there are outliers at the higher end of
# unit price, which are heavily influencing the regression line for units sold.
# For the regression line, 
# Intercept:  3.28532 | Coefficient of art$unit.price: -0.06681

################################################################################################

# Question 2: Does the art company sell more units of drawing paper or watercolor paper?

# units.by.paper <- aggregate(x = art$units.sold
#                           , by = list(art$paper)
#                           , FUN = sum)
# units.by.paper
# colnames(units.by.paper) <- c("Paper","Units Sold")

# barplot(as.matrix(units.by.paper), main = "Barplot of Units sold by Paper"
#        , ylab = "Number of Units") # Not able to correctly explain whether the units sold are 
# higher in drawing paper or watercolor paper

units.by.paper <- tapply(X=art$units.sold
                       , INDEX=list(art$paper)
                       , FUN = sum)
units.by.paper
tmp1 <- barplot(units.by.paper, main = "Barplot of Units sold by Paper"
        , ylab = "Number of Units", col = "indianred", ylim = c(0,20000))
tmp1
units.by.paper1 <- as.numeric(paste(units.by.paper)) # Converted to numeric from array 
# to use for labeling
# Labels
text(tmp1[1,], units.by.paper1[1] + 1000, units.by.paper1[1])
text(tmp1[2,], units.by.paper1[2] + 1000, units.by.paper1[2])

# Answer: The company sells more units of watercolor paper as compared to drawing paper.

###############################################################################################

# Question 3: Does the art company bring in more money (revenue) selling drawing paper 
# or watercolor paper?

revenue.by.paper <- tapply(X=art$total.sale
                           , INDEX=list(art$paper)
                           , FUN = sum)
revenue.by.paper
options(scipen = 99)
par(xpd=NA)
tmp2 <- barplot(revenue.by.paper, main = "Revenue generated by Paper"
                , ylab = "Revenue (in Dollars)", col = "indianred4",ylim=c(0,120000))
tmp2
revenue.by.paper1 <- as.numeric(paste(revenue.by.paper)) 
text(tmp2[1,], revenue.by.paper1[1] + 5000, round(revenue.by.paper1[1],0))
text(tmp2[2,], revenue.by.paper1[2] + 5000, round(revenue.by.paper1[2],0))

# Answer: The company generates more revenue by selling watercolor paper as compared to 
# drawing paper.

#############################################################################################

# Question 4: Each paper (watercolor and drawing) has different subtypes. 
# It is possible that at some stores, some subtypes sell better than others. 
# For drawing paper only, make a plot that allows the viewer to compare which subtypes 
# of drawing paper sell more (and less) units across the stores.

drawing.paper <- subset(art,art$paper == "drawing")
drawing.paper.sold.by.subtype <- tapply(X=drawing.paper$units.sold
                                , INDEX = list(drawing.paper$paper.type,drawing.paper$store)
                                , FUN = sum)
drawing.paper.sold.by.subtype

tmp3 <- barplot(drawing.paper.sold.by.subtype, beside = T, las=2, main="Drawing paper 
                by Type and Store", ylim = c(0,1200), ylab = "Number of Units Sold"
                , col = c("indianred","orangered","red4","tomato3"))
legend("topright",c("journal","pads","roll","sheet")
       , fill = c("indianred","orangered","red4","tomato3"))

# Answer: Yes, different subtypes sell differently at each store.
# Following are the figures:
#          Davenport Dublin Portland Syracuse
# journal       365    281      479      409
# pads          769    538      981      781
# roll          137     87      221      155
# sheet         330    344      438      261

# In Davenport, Pads > Journal > Sheet > Roll
# In Dublin, Pads > Sheet > Journal > Roll
# In Portland, Pads > Journal > Sheet > Roll
# In Syracuse, Pads > Journal > Sheet > Roll

#############################################################################################

# Question 5: The dataset covers 4 years of data. Compare the revenue gained each year from
# the sales drawing paper with that of watercolor paper. Are sales growing over time for both?

par(mfrow=c(1,1))
A <- tapply(art$total.sale, INDEX = list(art$paper, art$year), FUN = sum)
A

B <- as.integer(colnames(A))
options(scipen = 99)
par(xpd = NA)
plot(B, A[1, ], type="l", ylim=c(0,40000), ylab = "Revenue (in Dollars)"
     , xlab = "Year", bty="n", col="red", lwd=3, main = "Revenue over time", xaxt = "n")
axis(1, at = seq(2012,2015, by = 1))
text(B[2], A[1,1]+2000, labels = rownames(A)[1], cex = 1.2)

lines(B,A[2, ], col="blue", lwd=3)
text(B[2], A[2,2]+2000, labels = rownames(A)[2], cex = 1.2)

# Answer: Following are the sales for each paper over time:
#               2012     2013     2014     2015
# drawing    19240.81 20058.88 21641.22 21893.27
# watercolor 24799.06 28436.71 30954.84 31151.47
# Judging by the plot, the sales for each paper is growing over time. 
# However, the rate of growth for each paper has slowed down in the period 2014-15.

